In [1]:
import numpy as np

In [2]:
array_empty = np.empty((2,3))

In [3]:
array_empty

array([[8.e-322, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

In [4]:
#Identity matrix implementation

In [5]:
array_eye = np.eye(3)

In [6]:
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#arange function and req: to print out only even numbers between 1 and 30

In [8]:
array_even = np.arange(2,31,2)

In [9]:
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [10]:
for x in  array_even: #giving this in a for loop
    print(x)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
