In [1]:
import numpy as np

In [2]:
array_of_floats = np.arange(0,2,0.3)

In [3]:
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [4]:
print(array_of_floats) #just trying to use print here and see how the ouput looks like.

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [5]:
#two dimensional array

In [9]:
array_2d = np.array([(1,2,3),(3,4,5),(4,5,6),(7,8,9)])

In [10]:
array_2d

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array_2d.shape #to know the shape of that array.

(4, 3)

In [12]:
array_nd = np.arange(6)

In [13]:
array_nd

array([0, 1, 2, 3, 4, 5])

In [14]:
array_nd = np.arange(6).reshape(3,2) #converting one dimension to two dimensional array.

In [15]:
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
array_3d = np.arange(30).reshape(2,3,5)

In [17]:
array_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [18]:
array_3d.shape

(2, 3, 5)