In [1]:
#Statistical functions of numpy:

In [2]:
import numpy as np

In [4]:
test_scores = np.array([32.32,56.98,21.52,44.32,55.55,70.50])

In [5]:
print('Mean test scores of the students: ')
print(np.mean(test_scores))

Mean test scores of the students: 
46.865


In [6]:
salaries = np.genfromtxt('salary.csv',delimiter=',')

In [7]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [8]:
salaries.shape  #to see how many lines of information

(1147,)

In [9]:
#req to find mean, median, standard deviation and variance.

In [10]:
mean = np.mean(salaries)
median = np.median(salaries)
sd = np.std(salaries)
variance = np.var(salaries)

In [12]:
print('Mean = %i' %mean)
print('Median = %i' %median)
print('Standard deviation = %i' %sd)
print('Variance = %i' %variance)

Mean = 55894
Median = 48000
Standard deviation = 55170
Variance = 3043770333


In [13]:
#Looping through numpy

In [14]:
a = np.arange(11)**2

In [15]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [16]:
print(a)

[  0   1   4   9  16  25  36  49  64  81 100]


In [17]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [19]:
#Looping through Multi dimensional arrays

In [21]:
Bank_customers = np.array([['ram','arun','raji','prem','amal'],
                           [5000,3000,6000,8000,9000],
                           [71,64,87,35]])

In [23]:
for i in Bank_customers:
    print('i = ', i)

i =  ['ram', 'arun', 'raji', 'prem', 'amal']
i =  [5000, 3000, 6000, 8000, 9000]
i =  [71, 64, 87, 35]


In [24]:
for i in Bank_customers:
    print(i)

['ram', 'arun', 'raji', 'prem', 'amal']
[5000, 3000, 6000, 8000, 9000]
[71, 64, 87, 35]


In [25]:
#Req: to split them entirely out of the loop.

In [28]:
for element in Bank_customers.flatten():
    print(element)

['ram', 'arun', 'raji', 'prem', 'amal']
[5000, 3000, 6000, 8000, 9000]
[71, 64, 87, 35]
